src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[UniqueEntity('email')]
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\EntityListeners(['App\EntityListener\UserListener'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    #[Assert\Length(min: 2, max: 50)]
    #[Assert\NotBlank()]
    private ?string $Nom = null;

    #[ORM\Column(length: 50, nullable: true)]
    #[Assert\Length(min: 2, max: 50)]
    private ?string $pseudo = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\Email()]
    #[Assert\Length(min: 2, max: 180)]
    private ?string $email = null;

    #[ORM\Column]
    #[Assert\NotNull()]
    private array $roles = [];

    private ?string $plainPassword = null;

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 8, minMessage:"Votre mot de passe doit être 8 caractéres")]
    private ?string $password = 'password';

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\NotNull()]
    private ?\DateTimeInterface $dateCreation = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\NotNull()]
    private ?\DateTimeInterface $dateUpdate;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Ingredient::class, orphanRemoval: true)]
    private Collection $Ingredients;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Recipe::class, orphanRemoval: true)]
    private Collection $recipes;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Mark::class, orphanRemoval: true)]
    private Collection $marks;

    public function __construct()
    {
        $this->dateCreation = new \DateTimeImmutable();
        $this->dateUpdate = new \DateTimeImmutable();
        $this->Ingredients = new ArrayCollection();
        $this->recipes = new ArrayCollection();
        $this->marks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(?string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * Get the value of plainPassword
     */ 
    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    /**
     * Set the value of plainPassword
     *
     * @return  self
     */ 
    public function setPlainPassword($plainPassword)
    {
        $this->plainPassword = $plainPassword;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(\DateTimeInterface $dateCreation): self
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    public function getDateUpdate(): ?\DateTimeInterface
    {
        return $this->dateUpdate;
    }

    public function setDateUpdate(\DateTimeInterface $dateUpdate): self
    {
        $this->dateUpdate = $dateUpdate;

        return $this;
    }

    /**
     * @return Collection<int, Ingredient>
     */
    public function getIngredients(): Collection
    {
        return $this->Ingredients;
    }

    public function addIngredient(Ingredient $ingredient): self
    {
        if (!$this->Ingredients->contains($ingredient)) {
            $this->Ingredients[] = $ingredient;
            $ingredient->setUser($this);
        }

        return $this;
    }

    public function removeIngredient(Ingredient $ingredient): self
    {
        if ($this->Ingredients->removeElement($ingredient)) {
            // set the owning side to null (unless already changed)
            if ($ingredient->getUser() === $this) {
                $ingredient->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Recipe>
     */
    public function getRecipes(): Collection
    {
        return $this->recipes;
    }

    public function addRecipe(Recipe $recipe): self
    {
        if (!$this->recipes->contains($recipe)) {
            $this->recipes[] = $recipe;
            $recipe->setUser($this);
        }

        return $this;
    }

    public function removeRecipe(Recipe $recipe): self
    {
        if ($this->recipes->removeElement($recipe)) {
            // set the owning side to null (unless already changed)
            if ($recipe->getUser() === $this) {
                $recipe->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Mark>
     */
    public function getMarks(): Collection
    {
        return $this->marks;
    }

    public function addMark(Mark $mark): self
    {
        if (!$this->marks->contains($mark)) {
            $this->marks[] = $mark;
            $mark->setUser($this);
        }

        return $this;
    }

    public function removeMark(Mark $mark): self
    {
        if ($this->marks->removeElement($mark)) {
            // set the owning side to null (unless already changed)
            if ($mark->getUser() === $this) {
                $mark->setUser(null);
            }
        }

        return $this;
    }
}

templates/pages/recette/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Recettes | Recettes {% endblock %}

{% block body %}
    <div class="container mt-4">
    <a href="{{ path('recipe.new') }}" class="btn btn-primary"><i class="bi bi-plus-square"></i> Créer une recettes</a>
    {% if not recipes.items is same as([]) %}
        <h1>Mes Recettes</h1>

        <div class="count">
            {{ recipes.getTotalItemCount }} Recettes
        </div>
        {% for message in app.flashes('Succes') %}
        <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
            <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
            </symbol>
            <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
                <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
            </symbol>
            <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
                <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
            </symbol>
        </svg>
        <div class="alert alert-success d-flex align-items-center mt-4" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
            <div>
                {{ message }}
            </div>
        </div>
        {% endfor %}
        {% for message in app.flashes('Warning') %}
        <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
            <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
            </symbol>
            <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
                <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
            </symbol>
            <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
                <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
            </symbol>
        </svg>
        <div class="alert alert-danger d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <div>
                {{ message }}
            </div>
        </div>
        {% endfor %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">ID</font></font></th>
                    <th scope="col"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Nom</font></font></th>
                    <th scope="col"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Prix</font></font></th>
                    <th scope="col"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Description</font></font></th>
                    <th scope="col"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Favorie</font></font></th>
                    <th scope="col" class="center"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Edition</font></font></th>
                    <th scope="col" class="center">Suppresion</th>
                    <th scope="col" class="center"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">details</font></font></th>
                </tr>
            </thead>
            <tbody>
            {% for recipe in recipes %}
                <tr class="table-active">
                    <th scope="row"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{ recipe.id }}</font></font></th>
                    <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{ recipe.nom }}</font></font></td>
                    <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{(recipe.prix is same as(null))? 'Non rensegné' : recipe.prix}}</font></font></td>
                    <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{ recipe.description|slice(0, 20) ~ ' ...'}}</font></font></td>
                    {# <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{ recipe.time }}</font></font></td> #}
                    <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{recipe.isFavorie }}</font></font></td>
                    
                    {# <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">{{ recipe.getDateCreation()|date('d/m/Y') }}</font></font></td>   #}
                    
                    <td>
                        <a href="{{ path('recipe.update', {'id' : recipe.id}) }}" class="btn btn-secondary"><i class="bi bi-pen"></i></a>
                    </td>
                    <td>
                        <a href="{{ path('recipe.delete', {'id' : recipe.id}) }}" class="btn btn-primary"><i class="bi bi-trash3-fill"></i></a>
                    </td>
                    <td>
                        <a href="{{ path('recipe.show', {'id' : recipe.id}) }}" class="btn btn-primary"><i class="bi bi-three-dots"></i></a>
                    </td>
                </tr>
            {% endfor %}  
            </tbody>
        </table>
        <div class="navigation">
            {{ knp_pagination_render(recipes) }}
        </div>
        {% else %}
            <h4>Il faut ajouter des Recettes</h4>
            <table class="table table-hover">
            <thead>
                <tr>
                <th scope="col"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">ID</font></font></th>
                <th scope="col"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Nom</font></font></th>
                <th scope="col"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Prix</font></font></th>
                <th scope="col"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Date Creation</font></font></th>
                </tr>
            </thead>
        </table>
        {% endif %}
    </div>
{% endblock %}

templates/pages/recette/new.html.twig
{% extends "base.html.twig" %}
{% block title %} Recettes | Nouveau Recettes {% endblock %}
{% block body %}
    <div class="container mb-4">
        <div class="row justify-content-evenly">
            <div class="col-6">
                <h1 class="mt-4">
                    Creation d'une Recette
                </h1>
                {{ form_start(form) }}
                    <div class="form-group">
                        {{ form_label(form.nom)}}
                        {{ form_widget(form.nom)}}
                        <div class="form-error">
                            {{ form_errors(form.nom) }}
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form_label(form.nbPersonne)}}
                        {{ form_widget(form.nbPersonne)}}
                        <div class="form-error">
                            {{ form_errors(form.nbPersonne) }}
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form_label(form.prix)}}
                        {{ form_widget(form.prix)}}
                        <div class="form-error">
                            {{ form_errors(form.prix) }}
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form_label(form.time)}}
                        {{ form_widget(form.time)}}
                        <div class="form-error">
                            {{ form_errors(form.time) }}
                        </div>
                    </div>
                    
                    <div class="form-group">
                        {{ form_label(form.difficulty)}}
                        {{ form_widget(form.difficulty)}}
                        <div class="form-error">
                            {{ form_errors(form.difficulty) }}
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form_label(form.description)}}
                        {{ form_widget(form.description)}}
                        <div class="form-error">
                            {{ form_errors(form.description) }}
                        </div>
                    </div>
                    <div class="form-check mt-4">
                        {{ form_label(form.isFavorie)}}
                        {{ form_widget(form.isFavorie)}}
                        <div class="form-error">
                            {{ form_errors(form.isFavorie) }}
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form_row(form.imageFile)}}
                    </div>
                    <div class="form-group">
                        {{ form_label(form.ingredients)}}
                        {{ form_widget(form.ingredients)}}
                        <div class="form-error">
                            {{ form_errors(form.ingredients) }}
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form_row(form.submit)}}
                    </div>
                    
                {{ form_end(form) }}
            </div>
            <div class="col-6">
                {#  #}
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/recette/recette_public.html.twig
{% extends 'base.html.twig' %}

{% block title %} Recettes | Recettes Publique {% endblock %}

{% block body %}
    <div class="container mt-4">
    {# <a href="{{ path('recipe.new') }}" class="btn btn-primary">Créer une recettes</a> #}
    {% if not recipes.items is same as([]) %}
        <h1>Recettes de la communauté</h1>
        <div class="d-flex justify-content-center flex-wrap">
        {% for recipe in recipes %}
        <a href="{{ path('recipe.show',{'id': recipe.id}) }}" style="text-decoration:none;">
        <div class="row">
            <div class="col-sm-11">
                <div class="card border-dark mb-3" style="max-width: 20rem;">
                    <div class="card-header">Recette n° {{ recipe.id }}</div>
                    <div class="card-body">
                        <h4 class="card-title">{{ recipe.nom }}</h4>
                        <p class="card-text">{{ recipe.description|slice(0, 40) ~ ' ...' }}</p>
                    </div>
                </div>
            </div>
        </div>
        </a>
        {% endfor %}
        </div>
        {% else %}
            <h4>Il n'y pas des recettes publique disponible</h4>
        {% endif %}
    </div>
{% endblock %}

templates/pages/recette/show.html.twig
{% extends "base.html.twig" %}

{% block title %}
    Recettes | {{ recipe.nom }}
{% endblock %}

{% block body %}
    <div class="container">
    {% for message in app.flashes('Succes') %}
        <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
            <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
            </symbol>
            <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
                <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
            </symbol>
            <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
                <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
            </symbol>
        </svg>
        <div class="alert alert-success d-flex align-items-center mt-4" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
            <div>
                {{ message }}
            </div>
        </div>
        {% endfor %}
        {% for message in app.flashes('Warning') %}
        <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
            <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
            </symbol>
            <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
                <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
            </symbol>
            <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
                <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
            </symbol>
        </svg>
        <div class="alert alert-danger d-flex align-items-center mt-4" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
            <div>
                {{ message }}
            </div>
        </div>
        {% endfor %}
        <h1 class="mt-4">{{ recipe.nom }}</h1>
        <p>La moyenne de cette recette est de : {{ recipe.average|number_format(2, '.', ',') }}/5</p>
        <span class="badge bg-primary">Crée le {{ recipe.dateCreation|date('d/m/Y') }}</span>
        <p class="mt-4">Temps (en minute) : {{ (recipe.time is same as(null))? 'Non rensegné' : recipe.time}}</p>
        <p>Pour : {{ (recipe.nbPersonne is same as(null))? 'Personne Non rensegné' : recipe.nbPersonne ~ ' personne(s)'}}</p>
        <p>Difficulté : {{ (recipe.difficulty is same as(null))? 'Non rensegné' : recipe.difficulty ~ '/5'}}</p>
        <p>Prix (en $) : {{(recipe.prix is same as(null))? 'Non rensegné' : recipe.prix}}</p>
        <div><p>{{ recipe.description|raw }}</p></div>
        <div class="recipe__image">
            <img style="max-width: 500px" src="{{ vich_uploader_asset(recipe, 'imageFile') }}" alt="image">
        </div>
        <h4 class="mt-4"> Ingrédient </h4>
        {% for ingredient in recipe.ingredients %}
            <span class="badge bg-dark">{{ ingredient.nom }}</span>
        {% endfor %}

        <div>
            {{ form(form) }}
        </div>
    </div>
{% endblock %}

templates/pages/recette/update.html.twig
{% extends "base.html.twig" %}
{% block title %} Recettes | Modifier une recette {% endblock %}
{% block body %}
    <div class="container">
        <div class="row justify-content-evenly">
            <div class="col-6">
                <h1 class="mt-4">
                Editer un Recette
                </h1>
                <form name="recipe" method="post">
                    <div class="form-group">
                        {{ form_label(form.nom)}}
                        {{ form_widget(form.nom)}}
                        <div class="form-error">
                            {{ form_errors(form.nom) }}
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form_label(form.nbPersonne)}}
                        {{ form_widget(form.nbPersonne)}}
                        <div class="form-error">
                            {{ form_errors(form.nbPersonne) }}
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form_label(form.prix)}}
                        {{ form_widget(form.prix)}}
                        <div class="form-error">
                            {{ form_errors(form.prix) }}
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form_label(form.time)}}
                        {{ form_widget(form.time)}}
                        <div class="form-error">
                            {{ form_errors(form.time) }}
                        </div>
                    </div>
                    
                    <div class="form-group">
                        {{ form_label(form.difficulty)}}
                        {{ form_widget(form.difficulty)}}
                        <div class="form-error">
                            {{ form_errors(form.difficulty) }}
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form_label(form.description)}}
                        {{ form_widget(form.description)}}
                        <div class="form-error">
                            {{ form_errors(form.description) }}
                        </div>
                    </div>
                    <div class="form-group">
                        {{ form_label(form.isFavorie)}}
                        {{ form_widget(form.isFavorie)}}
                        <div class="form-error">
                            {{ form_errors(form.isFavorie) }}
                        </div>
                    </div>
                        {{ form_row(form.imageFile)}}
                    <div class="form-group">
                        {{ form_label(form.ingredients)}}
                        {{ form_widget(form.ingredients)}}
                        <div class="form-error">
                            {{ form_errors(form.ingredients) }}
                        </div>
                    </div>            
                    {{form_row(form._token)}}
                <button type="submit" id="recipe_submit" name="recipe[submit]" class="btn btn-primary mt-4">Modifier</button>
                </form>
            </div>
            <div class="col-6">
                {#  #}
            </div>
        </div>
    </div>
{% endblock %}